name: Deploy Edge Function to Supabase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Function
        run: |
          supabase functions deploy process-telegram-flow --project-ref nkoetzfiorwldqknttvx --no-verify-jwt
        env:
          # 🔑 സുപബേസ് ആക്സസ് ടോക്കൺ നേരിട്ട് ഇവിടെ നൽകുന്നു
          SUPABASE_ACCESS_TOKEN: sbp_7ccbdae8dfa44ce41d9bde46211a239bad1bd13c
